version: "2.1"
services:
  elastic:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    container_name: e621_elastic
    healthcheck:
      interval: 10s
      retries: 999
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/ || exit 1
    networks:
      default:
        ipv4_address: 172.99.0.1
  memcached:
    image: memcached
    container_name: e621_memcached
    networks:
      default:
        ipv4_address: 172.99.0.2
  e621:
    image: ubuntu:focal
    container_name: e621
    command: /home/danbooru/danbooru/script/install_prod/install.sh
    depends_on:
      elastic:
        condition: service_healthy
      memcached:
        condition: service_started
    volumes:
      - /opt/E621:/home/danbooru/danbooru:Z
      - /opt/E621/data/db:/var/lib/postgresql/12/main:Z
      - /opt/E621/data/redis:/var/lib/redis:Z
    environment:
      - RAILS_ENV=production
    restart: always
    ports:
      - 127.3.6.21:80:80
      - 127.3.6.21:443:443
    networks:
      default:
        ipv4_address: 172.99.0.3

networks:
  default:
    name: e621
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.99.0.0/24
          gateway: 172.99.0.255
