version: "3"
services:
  elastic:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    container_name: e621_elastic
  memcached:
    image: memcached
    container_name: e621_memcached
  e621:
    image: ubuntu:focal
    container_name: e621
    command: /home/danbooru/danbooru/script/install_prod/install.sh
    depends_on:
      - elastic
      - memcached
    volumes:
      - /opt/E621:/home/danbooru/danbooru:Z
      - /opt/E621/data/db:/var/lib/pgsql/data:Z
    environment:
      - RAILS_ENV=production
    restart: always
    ports:
      - 127.3.6.21:80:80
      - 127.3.6.21:443:443
