version: "2.1"
services:
  elastic:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    container_name: e621_elastic
    healthcheck:
      interval: 10s
      retries: 999
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/ || exit 1
  memcached:
    image: memcached
    container_name: e621_memcached
  e621:
    image: ubuntu:focal
    container_name: e621
    command: /home/danbooru/danbooru/script/install_prod/install.sh
    depends_on:
      elastic:
        condition: service_healthy
      memcached:
        condition: service_started
    volumes:
      - /opt/E621:/home/danbooru/danbooru:Z
      - /opt/E621/data/db:/var/lib/pgsql/data:Z
      - /opt/E621/data/redis:/var/lib/redis:Z
    environment:
      - RAILS_ENV=production
    restart: always
    ports:
      - 127.3.6.21:80:80
      - 127.3.6.21:443:443
