#!/usr/bin/env bash

until [ "`docker inspect -f {{.State.Health.Status}} fursuitbutts 2> /dev/null`" == "healthy" ]; do
    sleep 1;
done;

sudo docker exec -it fursuitbutts bundle exec rake assets:precompile
sudo docker-compose restart fursuitbutts
