#!/usr/bin/env bash
until [ "`docker inspect -f {{.State.Health.Status}} yiffyapi`" == "healthy" ]; do
    sleep 1;
done;

sudo docker exec -it yiffyapi bundle exec rake assets:precompile
sudo docker-compose restart yiffyapi
