#!/usr/bin/env bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

cd $SCRIPT_DIR
start=`date +%s`
docker-compose down -f $SCRIPT_DIR/docker/docker-compose.yml
end=`date +%s`
runtime=$((end-start))
echo "Down took $runtime seconds"
