#!/usr/bin/env bash

cd $(realpath "$(dirname "${BASH_SOURCE[0]}")")/..
sudo rm -f tmp/pids/server.pid
sudo docker-compose --env-file .env.production up $1
sudo docker exec -it yiffyapi bundle exec rake assets:precompile
sudo docker-compose restart yiffyapi
