#!/usr/bin/env bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

cd $SCRIPT_DIR
git pull
start=`date +%s`
docker-compose -f $SCRIPT_DIR/../docker/docker-compose.yml up
end=`date +%s`
runtime=$((end-start))
echo "UP (Interactive) took $runtime seconds"
