version: "2.1"
services:
  elastic:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    container_name: yiffyapi_elastic
    mem_limit: 16gb
    healthcheck:
      interval: 10s
      timeout: 2s
      retries: 999
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/ || exit 1
    networks:
      default:
        ipv4_address: 172.31.0.2
  memcached:
    image: yiffyapi/memcached
    container_name: yiffyapi_memcached
    healthcheck:
      interval: 10s
      timeout: 2s
      retries: 999
      test: nc -z 127.0.0.1 11211
    networks:
      default:
        ipv4_address: 172.31.0.3
  e621:
    image: ubuntu:focal
    container_name: yiffyapi
    command: /home/danbooru/danbooru/script/install/prod.sh
    depends_on:
      elastic:
        condition: service_healthy
      memcached:
        condition: service_healthy
    volumes:
      - /opt/YiffyAPI:/home/danbooru/danbooru
      - /opt/YiffyAPI/data/redis:/var/lib/redis
      - /opt/YiffyAPI/data/db:/var/lib/postgresql
      - /opt/YiffyAPI/data/db_config:/etc/postgresql
      - /var/www/yiffy-api:/data
    environment:
      - RAILS_ENV=production
    restart: always
    ports:
      - 127.3.6.21:80:80
      - 127.3.6.21:443:443
    healthcheck:
      interval: 10s
      timeout: 2s
      retries: 999
      test: lsof -i :9000 || exit 1
    networks:
      default:
        ipv4_address: 172.31.0.4

networks:
  default:
    name: yiffyapi
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.1
