# frozen_string_literal: true

class UpdatersCreatorsAndIpAddrs < ExtendedMigration[7.1]
  def change
    add_ip_addr(:artists, :creator)
    add_ip_addr(:bans, :banner)
    rename_column(:dmails, :creator_ip_addr, :from_ip_addr)
    rename_column(:edit_histories, :ip_addr, :updater_ip_addr)
    rename_column(:edit_histories, :user_id, :updater_id)
    rename_column(:user_events, :ip_addr, :user_ip_addr)
    add_ip_addr(:forum_posts, :updater)
    add_ip_addr(:forum_topics, :updater)
    add_ip_addr(:ip_bans, :creator)
    add_ip_addr(:mascots, :creator)
    add_ip_addr(:mod_actions, :creator)
    add_ip_addr(:news_updates, :creator)
    add_ip_addr(:news_updates, :updater)
    add_ip_addr(:notes, :creator)
    add_ip_addr(:pools, :creator)
    add_ip_addr(:post_events, :creator)
    add_ip_addr(:staff_audit_logs, :user)
    add_ip_addr(:tag_versions, :updater)
    add_ip_addr(:user_feedbacks, :updater)
    add_ip_addr(:wiki_pages, :creator)
    add_ip_addr(:email_blacklists, :creator)
    add_ip_addr(:post_disapprovals, :user)
    add_ip_addr(:post_approvals, :user)
    add_ip_addr(:post_replacement_rejection_reasons, :creator)
    add_ip_addr(:post_deletion_reasons, :creator)
    add_ip_addr(:rule_categories, :creator)
    add_ip_addr(:rule_categories, :updater)
    add_ip_addr(:rules, :creator)
    add_ip_addr(:rules, :updater)
    add_ip_addr(:staff_notes, :creator)
    add_ip_addr(:staff_notes, :updater)
    add_ip_addr(:user_approvals, :updater, null: true)
    add_ip_addr(:wiki_pages, :updater)
    add_ip_addr(:tickets, :handler, null: true)
    add_defaulted_user_column(:bulk_update_requests, :updater, :creator)
    add_defaulted_user_column(:user_name_change_requests, :creator, :user)
    add_defaulted_user_column(:posts, :updater, :uploader)
    add_defaulted_user_column(:mascots, :updater, :creator)
    add_updater_column(:tag_aliases)
    add_updater_column(:post_deletion_reasons)
    add_updater_column(:post_appeals)
    add_creator_column(:forum_categories)
    add_updater_column(:forum_categories)
    add_updater_column(:post_replacement_rejection_reasons)
    add_updater_column(:post_sets)
    add_updater_column(:tag_implications)
    add_updater_column(:takedowns, nil, null: true)
    add_creator_column(:upload_whitelists)
    add_updater_column(:upload_whitelists)
    add_creator_column(:help_pages)
    add_updater_column(:help_pages)
    add_creator_column(:quick_rules)
    add_creator_column(:tags)
    add_updater_column(:quick_rules)
  end
end
